# Generated by Django 2.0.6 on 2018-11-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('number', models.TextField()),
                ('suburb', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
    ]
